version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user_api
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: db_restapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=user_api
      - DB_PASSWORD=password_rahasia
      - DB_NAME=db_restapi
      - DB_PORT=5432
    depends_on:
      - db
    command: npm run dev

volumes:
  postgres_data: